config/routes.rb
FlailWeb::Application.routes.draw do
  root :to => 'flail_exceptions#index'

  post '/swing' => 'flail_exceptions#create'

  resources :flail_exceptions
  resources :digests
  resources :web_hooks do
    collection do
      post :test
    end
  end
  resources :filters
end

app/models/web_hook.rb
require 'net/http'

class WebHook < ActiveRecord::Base
  EVENT_TYPES = ['exception', 'resolution']

  attr_accessible :secure, :url, :event

  validates :url, :presence => true
  validates :event, :presence => true

  module ClassMethods
    def trigger(event, exception, exception_url)
      payload = case event
                when :exception
                  trigger_exception(exception)
                when :resolution
                  trigger_resolution(exception)
                end.merge(:url => exception_url)

      WebHook.where(:event => event).map do |hook|
        url = URI.parse(hook.url)

        http = Net::HTTP.new(url.host, url.port)

        http.read_timeout = 2
        http.open_timeout = 1

        if hook.secure
          http.use_ssl      = true
          http.verify_mode  = OpenSSL::SSL::VERIFY_NONE
        else
          http.use_ssl      = false
        end

        begin
          http.post(url.path, {:payload => payload}.to_json, {'Content-type' => 'application/json', 'Accept' => 'application/json'})
        rescue Exception => e
          Rails.logger.error e.inspect
          nil
        end
      end
    end

    def trigger_exception(exception)
      similar = FlailException.with_digest(exception.digest).count

      {
        :event => 'exception',
        :tag => exception.tag,
        :environment => exception.environment,
        :similar => similar,
        :exception => exception.class_name,
        :message => exception.message[0..128],
      }
    end

    def trigger_resolution(exception)
      similar = FlailException.with_digest(exception.digest).count

      {
        :event => 'resolution',
        :tag => exception.tag,
        :environment => exception.environment,
        :similar => similar,
        :exception => exception.class_name,
        :message => exception.message[0..128],
      }
    end
  end
  extend ClassMethods
end

app/controllers/web_hooks_controller.rb
class WebHooksController < ApplicationController
  inherit_resources

  def index
  end

  def create
    create! { web_hooks_url }
  end

  def test
    Rails.logger.info '--------------------------------------------'
    Rails.logger.info params.inspect
    Rails.logger.info '--------------------------------------------'

    render :nothing => true
  end
end

app/views/web_hooks/index.html.haml
%header.jumbotron
  %h1
    .pull-right
      = link_to('New Web Hook', new_web_hook_url, :class => 'btn btn-success')
    %span.text-quiet Exception /
    %span Web Hooks


- WebHook::EVENT_TYPES.map do |event|
  .row
    .span12
      .page-header
        %h2= event
      %table.table.table-striped.table-bordered
        %thead
          %tr
            %th.span1 Secure?
            %th URL
            %th.span1 Actions
        %tbody
          - if WebHook.where(:event => event).count == 0
            %tr
              %td{:colspan => 3}
                No web hooks registered.
          - WebHook.where(:event => event).all.map do |hook|
            %tr
              %td
                - if hook.secure
                  %i.icon.icon-check
                - else
                  %i.icon.icon-remove
              %td= hook.url
              %td= button_to('Remove', web_hook_url(hook), :class => 'btn btn-danger', :method => :delete)

app/views/web_hooks/new.html.haml
%header.jumbotron
  %h1
    %span.text-quiet Exception /
    %span Web Hooks


.row
  .span12
    = simple_form_for(@web_hook, :html => {:class => 'form-vertical'}) do |f|
      = f.input(:secure)
      = f.input(:url, :input_html => {:class => 'span6'})
      = f.input(:event, :collection => WebHook::EVENT_TYPES)
      .form-actions
        = f.submit