config/routes.rb
FlailWeb::Application.routes.draw do
  root :to => 'flail_exceptions#index'

  post '/swing' => 'flail_exceptions#create'

  resources :flail_exceptions
  resources :digests
  resources :web_hooks do
    collection do
      post :test
    end
  end
  resources :filters
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  include RequestParameters::Conversion

  LIMITING_PARAMETERS = [:class_name, :message, :request_params, :user_agent]
  GENERAL_PARAMETERS = [:target_url, :environment, :hostname, :tag]
  ALL_PARAMETERS = LIMITING_PARAMETERS + GENERAL_PARAMETERS
  REGULAR_PARAMETERS = ALL_PARAMETERS - [:request_params]
  HEADER_PARAMETERS = [:class_name, :message, :environment, :tag]
  OTHER_PARAMETERS = ALL_PARAMETERS - HEADER_PARAMETERS

  attr_accessible *ALL_PARAMETERS

  has_many :filtered_exceptions, :class_name => 'FlailException',
                                 :foreign_key => 'filtered_by'

  validate :has_at_least_one_limiting_parameter

  def request_params=(value)
    @request_params = RequestParameters(value)
    self.params_including = request_params.to_json

    @request_params
  end

  def request_params
    @request_params ||= RequestParameters.new(params_including)
  end

  def match?(flail_exception)
    matches_regular_parameters?(flail_exception) and
    matches_request_params?(flail_exception)
  end

  def parameters
    parameters_hash = HashWithIndifferentAccess.new

    ALL_PARAMETERS.each do |parameter|
      parameters_hash[parameter] = send(parameter)
    end

    parameters_hash
  end

  def parameters=(other_parameters)
    ALL_PARAMETERS.each do |parameter|
      value = other_parameters[parameter] || other_parameters[parameter.to_s]
      send("#{parameter}=", value)
    end

    parameters
  end

  def subset_with(filter_selector)
    filter = self.class.new(self.attributes.select {|k, v| ALL_PARAMETERS.include?(k.to_sym) })
    filter.request_params = request_params

    ALL_PARAMETERS.each do |parameter|
      filter.send("#{parameter}=", nil) unless filter_selector.send(parameter)
    end

    filter
  end

  def to_s
    parameters_hash.map {|k, v| "#{k}: #{v}" }.join("; ")
  end

  def exceptions_caught
    filtered_exceptions.size
  end

  def print_class_name
    class_name.blank? ? "<Any Exception Class>" : class_name
  end

  def print_environment
    environment.blank? ? "any environment" : environment
  end

  def print_message
    message.blank? ? "<Any error message>" : message
  end

  def print_tag
    tag.blank? ? "all projects" : tag
  end

  def other_parameters
    parameters = {}

    OTHER_PARAMETERS.each do |param_name|
      value = send(param_name)
      unless value.blank?
        parameters[param_name.to_s.titleize] = value
      end
    end

    parameters
  end

  def has_at_least_one_limiting_parameter
    unless LIMITING_PARAMETERS.detect {|parameter| !self.send(parameter).blank? }
      filter_list = LIMITING_PARAMETERS.to_sentence(last_word_connector: " or ")
      errors.add(:base, "A filter must include at least one of #{filter_list}")
    end
  end

  module ClassMethods
    def new_from_exception(flail_exception)
      return new if flail_exception.nil?

      attributes = {}
      REGULAR_PARAMETERS.each do |key|
        value = flail_exception.send(key)
        attributes[key] = value unless value.blank?
      end
      attributes["request_params"] = flail_exception.params

      new(attributes)
    end
  end
  extend ClassMethods

  private

  def matches_regular_parameters?(flail_exception)
    regular_parameters = REGULAR_PARAMETERS.reject {|parameter| self[parameter].blank? }
    regular_parameters.all? {|parameter| flail_exception[parameter] == self[parameter] }
  end

  def matches_request_params?(flail_exception)
    request_params.match?(flail_exception.params)
  end

  def parameters_hash
    ALL_PARAMETERS.inject({}) { |hsh, parameter|
      value = self.send(parameter)
      hsh[parameter] = value unless value.blank?

      hsh
    }
  end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  inherit_resources

  def show
    @filter = Filter.find(params[:id])
    @filtered_exceptions = FlailException.digested(@filter.filtered_exceptions)
    show!
  end

  def new
    fe = FlailException.find_by_digest(params[:digest])
    @filter = Filter.new_from_exception(fe)
    @filter_selector = FilterSelector.new
    new!
  end

  def create
    filter_selector_params = params[:filter].delete(:filter_selector)
    @filter_selector = FilterSelector.new(filter_selector_params)

    original_filter = Filter.new(params[:filter])
    @filter = original_filter.subset_with(@filter_selector)

    create! do |success, failure|
      success.html { redirect_to filters_url }
      failure.html {
        @filter.parameters = original_filter.parameters
        render action: "new", status: 422
      }
    end
  end

  def edit
    @filter = Filter.find(params[:id])
    @filter_selector = FilterSelector.from_filter(@filter)
    edit!
  end

  def update
    filter_selector_params = params[:filter].delete(:filter_selector)
    filter_selector = FilterSelector.new(filter_selector_params)

    @filter = Filter.find(params[:id])
    params[:filter] = filter_selector.nullify_unselected_parameters(params[:filter])

    update! do |success, failure|
      success.html { redirect_to filter_url(@filter) }
      failure.html {
        @filter_selector = FilterSelector.from_filter(@filter)
        render action: "edit", status: 422
      }
    end
  end
end

app/helpers/filters_helper.rb
module FiltersHelper
  def filter_form_for(filter, *args, &block)
    options = args.extract_options!
    simple_form_for(filter, *(args << options.merge(builder: FilterFormBuilder)), &block)
  end

  class FilterFormBuilder < SimpleForm::FormBuilder
    include ActionView::Helpers::TagHelper

    attr_accessor :filter_selector, :output_buffer

    def button(type, *args, &block)
      options = args.extract_options!
      options[:class] ||= 'btn btn-primary'
      super(type, *(args << options), &block)
    end

    def input(attribute_name, options = {}, &block)
      options[:wrapper_html] ||= {}
      options[:wrapper_html].merge!(:class => 'span6')
      super
    end

    def input_plus_check_box(attribute_name, options = {})
      html = []

      html << input(attribute_name, options)
      html << selector_check_box(attribute_name)

      content_tag(:div, :class => 'row') do
        html.join("\n").html_safe
      end
    end

    # You'll have to use #filter_selector= to set the filter selector before
    # this will work.
    def selector_check_box(attribute_name, text = "Include?")
      content_tag(:div, :class => 'span1') do
        fields_for(filter_selector) do |fs|
          fs.label(attribute_name, text) +
            fs.check_box(attribute_name, :data => {:'filter-selector' => "filter_#{attribute_name}"})
        end
      end
    end
  end
end

app/views/filters/_filter.html.haml
%tr
  %td= filter
  %td= filter.exceptions_caught
  %td.filter-actions
    = link_to("#{icon('icon-list-alt')} View".html_safe, filter, :class => 'btn btn-info')
    = link_to("#{icon('icon-edit')} Edit".html_safe, edit_filter_path(filter), :class => 'btn btn-warning')
    = simple_form_for(filter, :method => :delete) do |f|
      %button{:type => 'submit', :class => 'btn btn-danger'}== #{icon('icon-remove')} Remove

app/views/filters/_filtered_exception.html.haml
.well.well-exception{:id => "digest_#{filtered_exception.first.digest}"}
  .pull-right
    %p.label.label-info= filtered_exception.first.tag
    %p.label= filtered_exception.first.environment
  .occurences.pull-left
    %h2
      .text-danger= filtered_exception.first.occurrences.count
      %small occurrences
  %h4
    %span= link_to(filtered_exception.first.class_name, digest_url(filtered_exception.first.digest))
    %small== last occurence #{time_ago_in_words(filtered_exception.first.created_at)}
  %p.message= filtered_exception.first.message

app/views/filters/_form.html.haml
%header.jumbotron
  %h1
    %span.text-quiet Exception /
    %span Filters

.row
  .span12
    = filter_form_for(filter, :html => {:class => 'form-vertical'}) do |f|
      - f.filter_selector = filter_selector
      %fieldset
        %legend Limiting Parameters (at least one required)
        .control-group.error
          = f.error :base
        = f.input_plus_check_box(:class_name)
        = f.input_plus_check_box(:message, :input_html => {:class => 'span6', :rows => '3'})
        = f.input_plus_check_box(:user_agent, :input_html => {:class => 'span6'})
        = f.input_plus_check_box(:request_params, :label => "Request parameters to match (in JSON)")
      %fieldset
        %legend General Parameters
        = f.input_plus_check_box(:tag)
        = f.input_plus_check_box(:environment)
        = f.input_plus_check_box(:target_url, :input_html => {:class => 'span6'})
        = f.input_plus_check_box(:hostname)
      .form-actions
        = f.button :submit
        = link_to "#{icon('icon-ban-circle')} Cancel".html_safe, :back, :class => 'btn btn-danger'

app/views/filters/edit.html.haml
= render :partial => 'form', :locals => {:filter => resource, :filter_selector => @filter_selector}

app/views/filters/index.html.haml
%header.jumbotron
  %h1
    .pull-right
      = link_to('New Filter', new_filter_url, :class => 'btn btn-success')
    %span.text-quiet Exception /
    %span Filters

.row
  .span12
    %table.table.table-striped.table-bordered
      %thead
        %tr
          %th Filtered Parameters
          %th.span2 Exceptions Filtered
          %th.span4 Actions
      %tbody
        - if Filter.count == 0
          %tr
            %td{colspan: 3}
              No filters registered.
        = render collection

app/views/filters/new.html.haml
= render :partial => 'form', :locals => {:filter => resource, :filter_selector => @filter_selector}

app/views/filters/show.html.haml
%header.jumbotron
  %h1
    %span.text-quiet Exception /
    %span Filter

.row
  .span12
    .page-header
      .pull-right
        %p.label.label-info= resource.print_tag
        %p.label= resource.print_environment
      %h2
        = resource.print_class_name
        %small= resource.print_message

.row
  .span12
    .pull-right.button-list
      = link_to("#{icon('icon-edit')} Edit".html_safe, edit_filter_path(resource), :class => 'btn btn-warning')
      = simple_form_for(resource, :method => :delete) do |f|
        %button{:type => 'submit', :class => 'btn btn-danger'}== #{icon('icon-remove')} Remove
    %dl.exception-info.clearfix
      - resource.other_parameters.each do |param_name, param_value|
        %dt.text-quiet= param_name
        %dd= param_value
      %dt.text-quiet= "No other parameters set." if resource.other_parameters.empty?

.row
  .span12
    %h3 Filtered Exceptions
    %hr
    = render :partial => 'filtered_exception', :collection => @filtered_exceptions