config/routes.rb
FlailWeb::Application.routes.draw do
  root :to => 'flail_exceptions#index'

  post '/swing' => 'flail_exceptions#create'

  resources :flail_exceptions
  resources :digests
  resources :web_hooks do
    collection do
      post :test
    end
  end
  resources :filters
end

app/models/flail_exception.rb
require 'digest/md5'

class FlailException < ActiveRecord::Base
  serialize :user
  serialize :params
  serialize :backtrace

  has_many :occurrences, :class_name => 'FlailException', :foreign_key => 'digest', :primary_key => 'digest'
  belongs_to :filter, :foreign_key => 'filtered_by', :counter_cache => true

  scope :tagged, lambda {|tag| where(:tag => tag)}
  scope :unresolved, where(:resolved_at => nil)
  scope :with_digest, lambda {|digest| where(:digest => digest)}
  scope :within, lambda {|time| where("created_at >= ?", time)}

  before_create :set_digest

  def resolve!
    FlailException.with_digest(self.digest).update_all(:resolved_at => Time.now)
  end

  def check_against_filters!(filter_collection)
    matching_filter = filter_collection.detect {|filter| filter.match?(self) }
    if matching_filter
      self.resolve_with!(matching_filter)
    end
  end

  def resolved?
    resolved_at?
  end

  def resolve_with!(filter)
    self.resolved_at = Time.now
    self.filtered_by = filter.id

    save!
  end

  def set_digest
    bt = self.backtrace.first

    controller, action = if params.is_a?(Hash)
                           [params['controller'], params['action']]
                         else
                           ['controller', 'action']
                         end

    self.digest = Digest::MD5.hexdigest("#{tag}#{environment}#{class_name}:#{controller}:#{action}:#{bt[:file]}:#{bt[:number]}")
  end

  module ClassMethods
    def tags
      select('distinct tag').map(&:tag)
    end

    def digested(flail_exceptions)
      flail_exceptions.group_by(&:digest).sort_by do |digest, fes|
        fes.select(&:created_at).max
      end.reverse.inject([]) do |arr, (digest, fes)|
        arr << fes.sort_by(&:created_at).reverse
      end.sort_by do |fes|
        fes.first.created_at
      end.reverse
    end

    def swing!(params)
      fe = FlailException.new

      fe.target_url = params[:target_url]
      fe.referer_url = params[:referer_url]
      fe.user_agent = params[:user_agent]
      fe.environment = params[:environment]
      fe.hostname = params[:hostname]
      fe.tag = params[:tag]
      fe.class_name = params[:class_name]
      fe.message = params[:message]
      fe.params = params[:parameters] || {}
      fe.user = params[:user] || {}
      fe.backtrace = params[:trace] || []
      fe.rack = params[:rack] || {}

      fe.save!
      fe
    end
  end
  extend ClassMethods
end

app/controllers/flail_exceptions_controller.rb
class FlailExceptionsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create]

  inherit_resources

  has_scope :tagged, :only => [:index]
  has_scope :unresolved, :type => :boolean, :default => true, :only => [:index]

  def index
    index! do |format|
      format.json do
        range = (0..23).to_a.map do |index|
          (23 - index).hours.ago
        end

        scope = FlailException.within(24.hours.ago)
        scope = scope.tagged(params[:tagged]) unless params[:tagged].blank?

        group = scope.group_by do |fe|
          fe.created_at.strftime('%j/%H')
        end

        data = (0..23).to_a.inject([]) do |arr, index|
          fes = group[range[index].strftime('%j/%H')] || []

          arr << {
            :index => index,
            :x => index,
            :y => fes.size,
            :label => {
              :x => range[index].strftime('%l%p'),
              :y => fes.size.to_s
            }
          }
        end

        render :json => data
      end
    end
  end

  def create
    fe = FlailException.swing!(params)
    filtered = fe.check_against_filters!(Filter.all)
    WebHook.trigger(:exception, fe, digest_url(fe.digest)) unless filtered

    render :nothing => true
  end
end

app/views/flail_exceptions/index.html.haml
.subnav.subnav-fixed
  %ul.nav.nav-pills
    %li{:class => active?}= link_to(icon('icon-dashboard') + ' Dashboard', params.merge(:tagged => nil))
    - FlailException.tags.map do |tag|
      %li{:class => active?(tag)}= link_to(tag, params.merge(:tagged => tag))

%header.jumbotron
  %h1
    %span.text-quiet Exception /
    %span Overview

.row
  .span12
    .hide
      = link_to('last 24 hours', 'javascript:;', 'data-d3-target' => '#exceptions-chart', 'data-d3-source' => flail_exceptions_url(params), 'data-d3-type' => 'bar-chart', 'data-d3-active' => true)
    #exceptions-chart.d3-bar.d3-vertical
    .clearfix

.row
  .span12
    .page-header
      %h2 Unresolved Exceptions
    #exceptions-unresolved
      - FlailException.digested(collection).map do |fes|
        .well.well-exception{:id => "digest_#{fes.first.digest}"}
          .pull-right
            %p.label.label-info= fes.first.tag
            %p.label= fes.first.environment
          .occurences.pull-left
            %h2
              .text-danger= fes.first.occurrences.count
              %small occurrences
          %h4
            %span= link_to(fes.first.class_name, digest_url(fes.first.digest))
            %small== last occurence #{time_ago_in_words(fes.first.created_at)}
          %p.message= fes.first.message
          .clearfix
          .actions
            = simple_form_for(fes.first, :url => digest_url(fes.first.digest), :html => {:remote => true}) do |f|
              %button{:type => 'submit', :class => 'btn btn-success'}== #{icon('icon-check')} Resolve